FROM nginx:alpine

COPY docker/nginx/prod.conf /etc/nginx/conf.d/default.conf
COPY public /var/www/html/public

RUN mkdir -p /etc/nginx/ssl \
    && rm -f /etc/nginx/conf.d/default.conf.bak

EXPOSE 443
